# swagger.yaml
openapi: 3.0.0
info:
  title: Job Management API
  version: 1.0.0
paths:
  /api/jobs:
    get:
      summary: Get all job postings
      description: Returns a list of all job postings in the database.
      responses:
        '200':
          description: A JSON array of job postings.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Unique ID of the job posting.
                    title:
                      type: string
                      description: Title of the job posting.
                    location:
                      type: string
                      description: Location of the job posting.

  /api/companies:
    get:
      summary: Get all companies
      description: Returns a list of all companies in the database.
      responses:
        '200':
          description: A JSON array of companies.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Unique ID of the company.
                    name:
                      type: string
                      description: Name of the company.
                    industry:
                      type: string
                      description: Industry of the company.
